-- Credential mailbox lifecycle (Issue 6, see docs/credential-mailbox.md).

-- SHA-256 of a claim token the issuer places inside the encrypted payload.
-- Only the true recipient can decrypt the payload and present the preimage,
-- so claiming is exactly as hard as breaking the encryption. Nullable:
-- deliveries without one can never be claimed and age out via retention.
ALTER TABLE credential_deliveries ADD COLUMN claim_token_hash BYTEA;

-- Monotonic pickup cursor, same pagination contract as encrypted_notes.id.
ALTER TABLE credential_deliveries ADD COLUMN seq BIGINT
    GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX credential_deliveries_seq_idx
    ON credential_deliveries (seq);
CREATE INDEX credential_deliveries_hint_seq_idx
    ON credential_deliveries (recipient_hint, seq)
    WHERE claimed_at IS NULL;
